development: &default
  adapter: postgresql
  encoding: utf8
  database: dog_cat_classifier_development
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "") %>
